kind: pipeline
type: docker
name: Build and test

steps:
  - name: install dependencies
    image: node:lts-alpine
    commands:
      - yarn install
  - name: build
    image: node:lts-alpine
    commands:
      - yarn build

---
kind: pipeline
type: ssh
name: Deploy to production

clone:
  disable: true

server:
  host:
    from_secret: host
  user:
    from_secret: user
  ssh_key:
    from_secret: key

trigger:
  branch:
    - master

steps:
  - name: checkout and pull
    commands:
      - cd /home/scram-bot/bot-prod
      - git pull
  - name: deploy
    commands:
      - cd /home/scram-bot/bot-prod
      - docker-compose build
      - docker-compose down
      - docker-compose up -d

depends_on:
  - Build and test
