kind: pipeline
type: docker
name: Build and test

steps:
  - name: install dependencies
    image: node:lts-alpine
    commands:
      - yarn install
  - name: build
    image: node:lts-alpine
    commands:
      - yarn build

---
kind: pipeline
type: ssh
name: Deploy to production

clone:
  disable: true

server:
  host:
    from_secret: host
  user: scram-bot
  ssh_key:
    from_secret: key

trigger:
  branch:
    - master
  event:
    - push
    - promote

steps:
  - name: checkout and pull
    commands:
      - cd /home/jasonyu/prod/scram-bot
      - git checkout master
      - git pull
  - name: deploy
    commands:
      - cd /home/jasonyu/prod/scram-bot
      - docker-compose build
      - docker-compose down
      - docker-compose up -d

depends_on:
  - Build and test
