version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: scrambot:latest
    volumes:
      - bot-logs:/root/scram-bot/logs
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: scram
      POSTGRES_PASSWORD: scram
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./database/.:/docker-entrypoint-initdb.d
volumes:
  postgres: ~
  bot-logs:
