version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: scrambot:latest
  postgres:
    container_name: postgresql
    image: postgres:13-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
